Fix mozorg workflow when there are no errors

diff --git a/.github/workflows/mozorg.yaml b/.github/workflows/mozorg.yaml
--- a/.github/workflows/mozorg.yaml
+++ b/.github/workflows/mozorg.yaml
@@ -48,8 +48,8 @@ jobs:
           if-no-files-found: ignore
       - name: Fail on errors
         run: |
+          cat errors_vendors.txt || echo "No vendor errors"
+          cat errors_community.txt || echo "No community errors"
           if [ -f "errors_vendors.txt" ] || [ -f "errors_community.txt" ]; then
-            cat errors_vendors.txt
-            cat errors_community.txt
             exit 1
           fi
